### ISSUE TITLE
Positioning delay in motion

### ISSUE THREAD

**Issue by Today20180409** [VorpalBlade/quickmcl#18]
Hello, I wanted to replace AMCL with this package, but I had a problem.In the process of robot moving, each laser processing takes a lot of time, which leads to positioning delay. But I put likelihood_ num_ When beams is turned on, the delay problem will be alleviated, but it still can't meet the requirements, which is completely different from AMCL. Is this normal, please? What can I do to change that? Hope to get your help ，thanks. @VorpalBlade

[ INFO] [1622604936.906454767]: Sensor model took 515 ms
[ INFO] [1622604936.909437357]: Laser cloud processing took 521 ms
[ INFO] [1622604936.913094327]: Laser cloud processing took 3 ms
[ INFO] [1622604936.916572128]: Laser cloud processing took 3 ms
[ INFO] [1622604936.919894154]: Laser cloud processing took 3 ms
[ INFO] [1622604936.923857023]: Laser cloud processing took 3 ms
[ INFO] [1622604936.927586915]: Laser cloud processing took 3 ms
[ INFO] [1622604937.000761051]: Laser cloud processing took 12 ms
[ INFO] [1622604937.090635198]: Laser cloud processing took 3 ms
[ INFO] [1622604937.201118132]: Laser cloud processing took 13 ms
[ INFO] [1622604937.290968898]: Laser cloud processing took 3 ms
[ INFO] [1622604937.400704508]: Laser cloud processing took 12 ms
[ INFO] [1622604937.490612819]: Laser cloud processing took 3 ms
[ INFO] [1622604937.599952569]: Laser cloud processing took 11 ms
[ INFO] [1622604937.699796460]: Laser cloud processing took 11 ms
[ INFO] [1622604937.800352997]: Laser cloud processing took 12 ms
[ INFO] [1622604938.355880810]: Sensor model took 467 ms
[ INFO] [1622604938.359256935]: Resampling took 3 ms

**Comment by VorpalBlade** [comment]
Hi,

I no longer have easy access to robots (so I can't check). However I suspect the issue might be rather simple. For QuickMCL you must make sure to build with optimisation enabled as the Eigen library which is used performs poorly without it. This makes a massive difference.

If you build with catkin try `catkin clean && catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release && catkin build`

If you use catkin_make I believe (it has been a while) you can use: `catkin_make --cmake-args -DCMAKE_BUILD_TYPE=Release`

Please let me know if this helps. If you still want to build other parts of your workspace with Debug build it can be useful to overlay mutiple workspaces as described here: http://wiki.ros.org/catkin/Tutorials/workspace_overlaying

**Comment by Today20180409** [comment]
Thank you very much. It dose work.  The time consumption of the same parameter is reduced by at least 20 times.Now, even likelihood_ num_beams = 1000，Sensor model only took 20~40 ms . It's amazing. Thank you again for your help.  @VorpalBlade

**Comment by VorpalBlade** [comment]
I'll add something to the readme about this and then close the issue.
